### ISSUE TITLE
[Ceylin, Damla] Create profile page and edit top contributors part for web

### ISSUE THREAD

**Issue by serhan-cakmak** [bounswe/bounswe2024group9#273]
We need to implement the Profile Page for the web application, ensuring it meets the specified requirements. The page will include features such as displaying user information, allowing edits to the user's profile, and handling tabs for user questions, bookmarks, and (in the future) comments. Additionally, the "Top Contributors" section in the sidebar should reflect dynamic data.

* Implement a Profile Page that aligns with the existing style and functionality of the web application.

* Update the Top Contributors section in the sidebar to display dynamic data.

* Include loading and error handling similar to other pages (e.g., SearchResults.js).

* [x] Create the Profile Page with tabs for user questions, bookmarks, and comments
* [x] Add functionality to edit user name and upload profile picture.
* [x] Add account management actions: delete account and update password via email.
* [x] Implement loading and error states for the Profile Page.
* [x] Update the "Top Contributors" section to reflect real-time or backend data.

Deadline: 19.11.2024
Estimated effort: 12 hrs
Reviewer: @Mutti499 , @serhan-cakmak

**Comment by ceylingebes** [comment]
I have implemented the Profile page and make Profile button in navigation bar functional. I have implemented viewing and updating the user profile, including name and profile picture and tabs for user questions and bookmarks. While implementing the Profile page, I included functionality for listing a user's comments since it is included in the mockups we have prepared and more importantly it's in the requirements. However, this feature is currently commented out due to an issue in the backend.
While attempting to fetch user comments using the endpoint` /get_user_profile_by_username/<username>/`, the API does not return any field or related data for comments. I believe the User model in the backend does not currently support retrieving comments associated with a user.
Can you guys check this out @Mutti499 @serhan-cakmak and let me know when the issue is resolved?

**Comment by Mutti499** [comment]
Ye I am on it mate

**Comment by ceylingebes** [comment]
With the updates coming from @Mutti499 , I have implemented the dynamic Top Contributors on Feed page. Additionally, the contributors are clickable and navigates to the contributor's profile page. Profile page is not finalized yet, but includes basic components as it is. You can check it out on web-profile branch.

**Comment by ceylingebes** [comment]
I have also implemented the profile page uploading mechanism and added a default profile page to users, however, I have problems about backend structure of uploaded images. I am not sure how to access uploaded pictures via which link? Can we have a quick talk about it tomorrow? Thanks @Mutti499 @serhan-cakmak

**Comment by ceylingebes** [comment]
Last but not least, I think we should also discuss the performance criteria for backend requests. Apparently we are sending A LOT OF redundant and recurring request to backend server, especially in feed afaik. If we can optimize that, we can speed up our applications significantly.

**Comment by Mutti499** [comment]
Ye about images I really dont have a idea. I will investigate after my midterm today. Be chill, we got this
