### ISSUE TITLE
[Kristina] Annotation Web Update

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#327]
Annotations in the web currently have an unstable offset. Also, the users who have not written the annotation can attempt to edit and delete the observed annotation which should  not be allowed.

* [x] Fix the offset bug and make sure that many correct annotations can be made on a page.
* [x] Show the username in an annotation
* [x] Do not show annotation deletion and editing icons to users who are not the creators of the observed annotation

Deadline: 10.12.2024.
Estimated effort: 5hrs
Reviewer: @ceylingebes

**Comment by Mutti499** [comment]
We changed the Annotation endpoints for the username showing part and it is ready from backend side

**Comment by Mutti499** [comment]
Annotation fields also should have a language name field. I noticed it while updating profiles. Let's not forget that in our meeting.

**Comment by kristinatrajkovski** [comment]
![image](https://github.com/user-attachments/assets/05fd324f-0d2a-400e-ab8c-11a654eb638e)

I believe it is done, please check @ceylingebes

**Comment by ceylingebes** [comment]
Let me check and get back to you

**Comment by Mutti499** [comment]
I [changed the annotations database](https://github.com/bounswe/bounswe2024group9/issues/343) while this task is going on. But don't worry. I merged the changes to this branch so that It won't effect the result. Also I tested the features beforehand. It seems cool mate. You can control my annotation from javascript page.
<img width="390" alt="image" src="https://github.com/user-attachments/assets/193daf0f-39df-4e58-a6da-2bc11f2d6a1f" />

**Comment by kristinatrajkovski** [comment]
![image](https://github.com/user-attachments/assets/67308efb-98e2-458f-8623-8b015de7cad8)


Thanks for the updates @Mutti499 . I also checked your annotation and it works as intended (I can see it but cannot modify or delete it).
