### ISSUE TITLE
Communication Plan​

### ISSUE THREAD

**Issue by poyrazogluyigit** [bounswe/bounswe2024group9#5]
Determine communication channels, mark down meeting details etc.

**Comment by poyrazogluyigit** [comment]
Arrangements for additional meeting

**Comment by ceylingebes** [comment]
(Draft) (Please correct me if anything is overlooked or misspelled)

Meeting schedule:
1. Task assignments & General meeting - Weekly - Thursdays 20.00 - Face to face - CMPE couches or CMPE Lounge
2. Additional meeting - To be scheduled if necessary - Subject to change (preferably weekends) - Online or face to face - Subject to change

Communication channels:
1. Github - Task management via issues and project documentation
2. Discord - Discussions about tasks, useful material exchange and online meetings
4. Whatsapp - Urgent communication and brainstoming


P.S.: This is an initial plan, meeting locations and times can be subject to change due to requests from team members.

**Comment by ceylingebes** [comment]
Communication plan wiki page is added. Check it out: [Communication Plan](https://github.com/bounswe/bounswe2024group9/wiki/Communication-Plan)
