### ISSUE TITLE
Feed: Add Requirements Related to the Feed to Github

### ISSUE THREAD

**Issue by kristinatrajkovski** [bounswe/bounswe2024group9#70]
The subteam in charge of the "Feed" page, Kristina and Halil, must review the decisions made by the team related to the requirements of the feed page, go over the answers given during the elicitation session with the course professor, formulate the necessary requirements and update the glossary when necessary.

* [x] Review the requirements related to the feed with the team.
* [x] Decide on format, hierarchy, titles
* [x] Add necessary words to the Glossary Wiki Page
* [x] Add to the Requirements Wiki page

Deadline: 16.03.2024.
Estimated duration: 3 hours

**Comment by halil-karabacak** [comment]
Since feed is a mostly user related section, some parts of it belong to functional and some part belongs to the system requirements section. We added the necessary information in User Requirements and Feed Requirements section in our requirements [page](https://github.com/bounswe/bounswe2024group9/wiki/Requirements).

**Comment by halil-karabacak** [comment]
Feed related words are added to our glossary [page](https://github.com/bounswe/bounswe2024group9/wiki/Glossary)
